In [176]:
import numpy as np

In [177]:
Xs = np.array([[0,1],[1,1],[2,1],[3,1]])

In [178]:
def create_transform(x_dim, y_dim):
    #account for bias
    f_x = np.random.rand(y_dim + 1, x_dim + 1)
    f_x[-1] = ([0]*x_dim) + [1]
    return f_x

In [179]:
#upscale
up1 = create_transform(1,2) # 1d (+ bias) -> 2d
up2 = create_transform(2,3) # 2d (+ bias) -> 3d
#then downscale
down1 = create_transform(3,2)
down2 = create_transform(2,1)

In [180]:
# the whole transform collapses into a simple single matrix
down2 @ down1 @ up2 @ up1

array([[1.54855532, 3.08140403],
       [0.        , 1.        ]])

In [181]:
#generate random 20 points as our x data
N = 20
Xs = np.random.rand(N)
#append bias and rotate it to the correct way
Xs = np.concatenate((Xs.reshape(1,-1), np.ones(N).reshape(1, -1)), axis=0).T
Xs

array([[0.43650542, 1.        ],
       [0.99759941, 1.        ],
       [0.43723327, 1.        ],
       [0.36581999, 1.        ],
       [0.40495531, 1.        ],
       [0.17491868, 1.        ],
       [0.17780113, 1.        ],
       [0.87785328, 1.        ],
       [0.55997853, 1.        ],
       [0.1644978 , 1.        ],
       [0.44860624, 1.        ],
       [0.51057318, 1.        ],
       [0.71756009, 1.        ],
       [0.76554367, 1.        ],
       [0.99521839, 1.        ],
       [0.6064134 , 1.        ],
       [0.53895931, 1.        ],
       [0.67707756, 1.        ],
       [0.73315477, 1.        ],
       [0.55735154, 1.        ]])

In [182]:
#generate our real y values
Ys = down2 @ down1 @ up2 @ up1 @ Xs.T
Ys.T

array([[3.75735681, 1.        ],
       [4.6262419 , 1.        ],
       [3.75848393, 1.        ],
       [3.64789651, 1.        ],
       [3.70849972, 1.        ],
       [3.35227528, 1.        ],
       [3.35673891, 1.        ],
       [4.44080838, 1.        ],
       [3.94856175, 1.        ],
       [3.33613797, 1.        ],
       [3.7760956 , 1.        ],
       [3.87205484, 1.        ],
       [4.19258552, 1.        ],
       [4.26689075, 1.        ],
       [4.62255475, 1.        ],
       [4.02046873, 1.        ],
       [3.91601233, 1.        ],
       [4.12989609, 1.        ],
       [4.21673475, 1.        ],
       [3.94449372, 1.        ]])

In [183]:
#now let's try and solve for a downscale (down1) node
#down2 @ down1 @ up2 @ up1

#first we need to go backwards through the down layer
downs = down2
inv_downs = np.linalg.pinv(downs)
back_downs = (inv_downs @ Ys).T[:,:2]

In [184]:
(down1 @ up2 @ up1 @ Xs.T).T

array([[1.60874723, 2.60874933, 1.        ],
       [2.08737593, 3.42596429, 1.        ],
       [1.60936811, 2.60980942, 1.        ],
       [1.5484506 , 2.50579832, 1.        ],
       [1.58183411, 2.56279763, 1.        ],
       [1.3856065 , 2.22775684, 1.        ],
       [1.38806531, 2.23195503, 1.        ],
       [1.98522916, 3.25155798, 1.        ],
       [1.71407321, 2.78858385, 1.        ],
       [1.37671721, 2.21257917, 1.        ],
       [1.61906956, 2.62637377, 1.        ],
       [1.67192908, 2.71662659, 1.        ],
       [1.84849464, 3.01809622, 1.        ],
       [1.88942597, 3.08798273, 1.        ],
       [2.08534485, 3.4224964 , 1.        ],
       [1.75368344, 2.85621472, 1.        ],
       [1.69614323, 2.75797005, 1.        ],
       [1.81396193, 2.95913475, 1.        ],
       [1.86179734, 3.04080936, 1.        ],
       [1.71183232, 2.78475773, 1.        ]])

In [185]:
back_downs

array([[2.33484585, 1.22649715],
       [3.04640889, 1.60028201],
       [2.33576889, 1.22698202],
       [2.24520465, 1.17940852],
       [2.29483492, 1.20547936],
       [2.00310918, 1.0522355 ],
       [2.00676462, 1.05415571],
       [2.89455033, 1.52051054],
       [2.49143085, 1.30875142],
       [1.98989373, 1.04529341],
       [2.35019176, 1.23455837],
       [2.42877643, 1.27583898],
       [2.69127119, 1.41372778],
       [2.75212257, 1.44569308],
       [3.04338934, 1.59869584],
       [2.5503182 , 1.33968501],
       [2.46477489, 1.29474902],
       [2.63993243, 1.38675947],
       [2.71104791, 1.42411651],
       [2.48809938, 1.3070014 ]])

In [186]:
# now forwards through the ups
ups = up2 @ up1
forw_ups = ups @ Xs.T

In [187]:
forw_ups.T

array([[0.95649901, 0.83783477, 1.63370509, 1.        ],
       [1.35635571, 1.00257368, 2.11671041, 1.        ],
       [0.9570177 , 0.83804847, 1.63433164, 1.        ],
       [0.9061259 , 0.81708131, 1.5728571 , 1.        ],
       [0.93401521, 0.82857156, 1.60654587, 1.        ],
       [0.77008244, 0.76103211, 1.40852394, 1.        ],
       [0.77213658, 0.7618784 , 1.41100523, 1.        ],
       [1.27102011, 0.96741585, 2.0136296 , 1.        ],
       [1.04449059, 0.87408686, 1.73999418, 1.        ],
       [0.76265613, 0.75797251, 1.39955336, 1.        ],
       [0.9651225 , 0.84138761, 1.64412181, 1.        ],
       [1.00928248, 0.85958129, 1.69746468, 1.        ],
       [1.15678915, 0.92035328, 1.87564477, 1.        ],
       [1.19098406, 0.93444141, 1.91695037, 1.        ],
       [1.3546589 , 1.00187461, 2.11466076, 1.        ],
       [1.07758183, 0.88772028, 1.77996661, 1.        ],
       [1.02951151, 0.86791555, 1.72190025, 1.        ],
       [1.12793977, 0.90846749,

In [188]:
forw_ups.shape

(4, 20)

In [189]:
back_downs.shape

(20, 2)

In [205]:
# now to solve down1 like a normal regression problem
# whoops!
# ((np.linalg.pinv(forw_ups @ forw_ups.T)) @ (forw_ups @ back_downs)).T
(np.linalg.pinv(forw_ups.T) @ back_downs).T

array([[0.64864251, 0.31061386, 0.83027819, 0.09774714],
       [0.34073264, 0.16316581, 0.43614606, 0.05134668]])

In [191]:
down1

array([[0.39152687, 0.14343518, 0.61789112, 0.10462531],
       [0.87125571, 0.52280254, 0.79235483, 0.04289784],
       [0.        , 0.        , 0.        , 1.        ]])

In [167]:
#now to solve down1 like a normal regression problem
appxd1 = (np.linalg.pinv(back_downs.T @ back_downs)) @ (back_downs.T @ forw_ups.T)

appxd1 = np.insert(appxd1, appxd1.shape[0], ([0]*(appxd1.shape[-1]-1)) + [1], axis=0)
appxd1

array([[0.53337033, 0.30836241, 0.3468824 , 0.46906102],
       [0.0886279 , 0.05123928, 0.05763999, 0.07794189],
       [0.        , 0.        , 0.        , 1.        ]])

In [168]:
appxd1

array([[0.53337033, 0.30836241, 0.3468824 , 0.46906102],
       [0.0886279 , 0.05123928, 0.05763999, 0.07794189],
       [0.        , 0.        , 0.        , 1.        ]])

In [169]:
appxd1.shape

(3, 4)

In [170]:
np.sum(np.abs(down1-appxd1))

2.7414850771926433

In [171]:
Ys_hat = down2 @ appxd1 @ up2 @ up1 @ Xs.T

In [172]:
down2 @ appxd1 @ up2 @ up1

array([[0.44647044, 1.36088334],
       [0.        , 1.        ]])

In [173]:
down2 @ down1 @ up2 @ up1

array([[0.43231558, 1.88968456],
       [0.        , 1.        ]])

In [174]:
Ys_hat.T

array([[1.65415855, 1.        ],
       [1.62631107, 1.        ],
       [1.44505419, 1.        ],
       [1.43968929, 1.        ],
       [1.74374522, 1.        ],
       [1.79455036, 1.        ],
       [1.73863937, 1.        ],
       [1.56885271, 1.        ],
       [1.40529989, 1.        ],
       [1.73647506, 1.        ],
       [1.45320843, 1.        ],
       [1.75291838, 1.        ],
       [1.6362273 , 1.        ],
       [1.37428912, 1.        ],
       [1.55715517, 1.        ],
       [1.74759623, 1.        ],
       [1.68045237, 1.        ],
       [1.51837992, 1.        ],
       [1.61448852, 1.        ],
       [1.5250251 , 1.        ]])

In [175]:
Ys.T

array([[2.1736618 , 1.        ],
       [2.14669719, 1.        ],
       [1.97118687, 1.        ],
       [1.96599205, 1.        ],
       [2.26040821, 1.        ],
       [2.30960263, 1.        ],
       [2.25546425, 1.        ],
       [2.09106049, 1.        ],
       [1.93269293, 1.        ],
       [2.25336855, 1.        ],
       [1.97908258, 1.        ],
       [2.26929055, 1.        ],
       [2.15629903, 1.        ],
       [1.90266533, 1.        ],
       [2.0797338 , 1.        ],
       [2.26413713, 1.        ],
       [2.19912199, 1.        ],
       [2.04218788, 1.        ],
       [2.13524946, 1.        ],
       [2.04862238, 1.        ]])