In [21]:
import numpy as np

In [22]:
X = np.matrix([[1, 1], 
               [1, 2],
              [1, 3],
              [1, 4]])
print(X)

[[1 1]
 [1 2]
 [1 3]
 [1 4]]


In [23]:
XT = np.matrix.transpose(X)
print(XT)

[[1 1 1 1]
 [1 2 3 4]]


In [24]:
y = np.matrix([[1], 
               [3],
              [3],
              [5]])
print(y)

[[1]
 [3]
 [3]
 [5]]


In [25]:
XT_X = np.matmul(XT, X)
print(XT_X)

[[ 4 10]
 [10 30]]


In [26]:
XT_y = np.matmul(XT, y)
print(XT_y)

[[12]
 [36]]


In [27]:
betas = np.matmul(np.linalg.inv(XT_X), XT_y)
print(betas)

[[0. ]
 [1.2]]


In [28]:
XT_y.shape

(2, 1)

In [29]:
np.linalg.inv(XT_X).shape

(2, 2)

In [30]:
XT.shape

(2, 4)

In [31]:
y.shape

(4, 1)

In [32]:
np.matmul(XT, y).shape

(2, 1)

In [34]:
np.linalg.inv(XT_X).shape

(2, 2)