In [7]:
import numpy as np

In [8]:
Xs = np.array([[0,1],[1,1],[2,1],[3,1]])

In [9]:
F_x = np.array([[2, 1], [0, 1]]) #function F(x) = 2x + 1

In [10]:
np.matmul(F_x, Xs.T)

array([[1, 3, 5, 7],
       [1, 1, 1, 1]])

In [14]:
G_x = np.array([[.5, -.5], [0, 1]]) #function G(x) = .5x + .5

In [15]:
np.matmul(G_x, Xs.T)

array([[-0.5,  0. ,  0.5,  1. ],
       [ 1. ,  1. ,  1. ,  1. ]])

In [17]:
np.matmul(G_x, np.matmul(F_x, Xs.T)) # Should just be y=x

array([[0., 1., 2., 3.],
       [1., 1., 1., 1.]])

In [18]:
#notice that I carry the bias vector throughout, this'll help convert existing models to linear appxs.

In [44]:
Ys = np.array([[0, 1], [1, 1], [2, 1], [3, 1]]) #np.array([[0, 1, 2, 3], [1, 1, 1, 1]])

In [46]:
np.linalg.pinv(Xs).dot(Ys)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [52]:
np.matmul(np.linalg.inv(F_x), np.matmul(np.linalg.inv(G_x), Ys.T))

array([[0., 1., 2., 3.],
       [1., 1., 1., 1.]])

In [53]:
# a non invertible matrix is one that "down samples to a lower dimension" essentially converting a higher dimensional vector to a lower one
N_x = np.array([[1,0,1],[0,0,1]])

In [55]:
np.linalg.pinv(N_x)

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00],
       [-2.39461108e-17,  1.00000000e+00]])

In [58]:
Z_x = np.array([[3,1],[2,1],[0,1]])
np.linalg.pinv(Z_x)

array([[ 0.28571429,  0.07142857, -0.35714286],
       [-0.14285714,  0.21428571,  0.92857143]])

In [59]:
np.matmul(np.linalg.pinv(F_x), np.matmul(np.linalg.pinv(G_x), Ys.T))

array([[5.55111512e-17, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [81]:
#solve for F_x

#this is the expected outputs for F_x given Xs
intermediate = np.matmul(np.linalg.pinv(G_x), Ys.T).T
intermediate

array([[1., 1.],
       [3., 1.],
       [5., 1.],
       [7., 1.]])

In [87]:
np.matmul(np.linalg.pinv(np.matmul(Xs.T, Xs)), Xs.T @ intermediate)

array([[ 2.0000000e+00, -8.8817842e-17],
       [ 1.0000000e+00,  1.0000000e+00]])

In [88]:
Xs.T @ intermediate

array([[34.,  6.],
       [16.,  4.]])