In [309]:
import numpy as np

In [310]:
def create_transform(x_dim, y_dim):
    #account for bias
    f_x = np.random.rand(y_dim + 1, x_dim + 1)
    f_x[-1] = ([0]*x_dim) + [1]
    return f_x

In [311]:
#upscale
up1 = create_transform(1,2) # 1d (+ bias) -> 2d
up2 = create_transform(2,3) # 2d (+ bias) -> 3d
#then downscale
down1 = create_transform(3,2)
down2 = create_transform(2,1)

In [312]:
# the whole transform collapses into a simple single matrix
down2 @ down1 @ up2 @ up1

array([[0.41694524, 1.41692947],
       [0.        , 1.        ]])

In [313]:
#generate random 20 points as our x data
N = 20
Xs = np.random.rand(N)
#append bias and rotate it to the correct way
Xs = np.concatenate((Xs.reshape(1,-1), np.ones(N).reshape(1, -1)), axis=0).T
Xs

array([[0.27559195, 1.        ],
       [0.64467367, 1.        ],
       [0.2186393 , 1.        ],
       [0.34027027, 1.        ],
       [0.91802133, 1.        ],
       [0.35644021, 1.        ],
       [0.57795113, 1.        ],
       [0.17909018, 1.        ],
       [0.75802954, 1.        ],
       [0.68819548, 1.        ],
       [0.76428694, 1.        ],
       [0.48635742, 1.        ],
       [0.35913533, 1.        ],
       [0.07296787, 1.        ],
       [0.08389505, 1.        ],
       [0.31488061, 1.        ],
       [0.43889591, 1.        ],
       [0.7709201 , 1.        ],
       [0.70380691, 1.        ],
       [0.25141426, 1.        ]])

In [314]:
#generate our real y values
Ys = down2 @ down1 @ up2 @ up1 @ Xs.T
Ys.T

array([[1.53183623, 1.        ],
       [1.68572309, 1.        ],
       [1.50809009, 1.        ],
       [1.55880354, 1.        ],
       [1.7996941 , 1.        ],
       [1.56554552, 1.        ],
       [1.65790345, 1.        ],
       [1.49160027, 1.        ],
       [1.73298628, 1.        ],
       [1.70386931, 1.        ],
       [1.73559528, 1.        ],
       [1.61971389, 1.        ],
       [1.56666924, 1.        ],
       [1.44735308, 1.        ],
       [1.45190911, 1.        ],
       [1.54821744, 1.        ],
       [1.59992503, 1.        ],
       [1.73836094, 1.        ],
       [1.71037841, 1.        ],
       [1.52175545, 1.        ]])

In [315]:
import scipy
import scipy.linalg

In [316]:
#now let's try and solve for a downscale (down1) node
#down2 @ down1 @ up2 @ up1
#first we need to go backwards through the down layer
downs = down2
inv_downs = np.linalg.pinv(downs)
back_downs = inv_downs @ Ys

In [317]:
(down1 @ up2 @ up1 @ Xs.T).T

array([[1.35752397, 2.28777139, 1.        ],
       [1.52033158, 2.58018668, 1.        ],
       [1.33240128, 2.24264906, 1.        ],
       [1.38605457, 2.33901459, 1.        ],
       [1.64090942, 2.79675398, 1.        ],
       [1.39318738, 2.35182568, 1.        ],
       [1.49089924, 2.52732388, 1.        ],
       [1.31495556, 2.21131517, 1.        ],
       [1.57033459, 2.66999602, 1.        ],
       [1.53952972, 2.61466804, 1.        ],
       [1.57309483, 2.67495362, 1.        ],
       [1.45049585, 2.45475621, 1.        ],
       [1.39437624, 2.35396096, 1.        ],
       [1.26814338, 2.1272368 , 1.        ],
       [1.27296353, 2.13589417, 1.        ],
       [1.3748548 , 2.31889892, 1.        ],
       [1.42955985, 2.4171535 , 1.        ],
       [1.57602082, 2.68020893, 1.        ],
       [1.54641616, 2.62703663, 1.        ],
       [1.34685882, 2.26861594, 1.        ]])

In [318]:
back_downs.T

array([[1.92359121, 1.61249268, 1.        ],
       [2.16317022, 1.81332505, 1.        ],
       [1.886622  , 1.58150243, 1.        ],
       [1.96557532, 1.64768679, 1.        ],
       [2.34060614, 1.96206463, 1.        ],
       [1.97607158, 1.65648551, 1.        ],
       [2.11985916, 1.77701861, 1.        ],
       [1.86094981, 1.55998214, 1.        ],
       [2.23675198, 1.87500659, 1.        ],
       [2.19142117, 1.83700704, 1.        ],
       [2.2408138 , 1.8784115 , 1.        ],
       [2.06040368, 1.72717874, 1.        ],
       [1.97782104, 1.65795203, 1.        ],
       [1.7920635 , 1.50223668, 1.        ],
       [1.79915657, 1.5081826 , 1.        ],
       [1.94909434, 1.63387124, 1.        ],
       [2.02959538, 1.701353  , 1.        ],
       [2.24511953, 1.88202087, 1.        ],
       [2.20155489, 1.84550185, 1.        ],
       [1.90789695, 1.59933662, 1.        ]])

In [319]:
# now forwards through the ups
ups = up2 @ up1
forw_ups = ups @ Xs.T

In [320]:
forw_ups.T

array([[1.37522471, 0.85818599, 1.2677186 , 1.        ],
       [1.62305237, 1.03757393, 1.39092109, 1.        ],
       [1.33698266, 0.83050481, 1.24870734, 1.        ],
       [1.41865432, 0.88962215, 1.28930875, 1.        ],
       [1.80659738, 1.17043142, 1.48216676, 1.        ],
       [1.42951197, 0.89748136, 1.29470641, 1.        ],
       [1.57825012, 1.0051442 , 1.36864856, 1.        ],
       [1.31042657, 0.81128241, 1.23550552, 1.        ],
       [1.69916754, 1.09266925, 1.4287602 , 1.        ],
       [1.652276  , 1.05872721, 1.40544902, 1.        ],
       [1.70336921, 1.09571058, 1.43084897, 1.        ],
       [1.5167476 , 0.96062613, 1.33807383, 1.        ],
       [1.43132166, 0.89879129, 1.29560606, 1.        ],
       [1.23916852, 0.75970288, 1.20008102, 1.        ],
       [1.2465058 , 0.76501391, 1.20372861, 1.        ],
       [1.4016059 , 0.87728179, 1.28083347, 1.        ],
       [1.48487857, 0.93755801, 1.32223079, 1.        ],
       [1.70782318, 1.09893456,

In [321]:
forw_ups.shape

(4, 20)

In [322]:
back_downs.shape

(3, 20)

In [323]:
# now to solve down1 like a normal regression problem
# whoops!
((np.linalg.pinv(forw_ups @ forw_ups.T)) @ (forw_ups @ back_downs.T)).T

array([[ 0.50638853,  0.31634105,  0.46536517,  0.36576165],
       [ 0.42449133,  0.26517985,  0.3901026 ,  0.30660776],
       [-0.08051731, -0.16076248,  0.39604124,  0.74662466]])

In [324]:
down1

array([[0.25048466, 0.38442733, 0.25785967, 0.35624763],
       [0.61791901, 0.44236561, 0.48637662, 0.44177324],
       [0.        , 0.        , 0.        , 1.        ]])

In [325]:
#now to solve down1 like a normal regression problem
appxd1 = (np.linalg.pinv(back_downs @ back_downs.T)) @ (back_downs @ forw_ups.T)

In [326]:
appxd1

array([[ 6.07523243e-01,  4.39750516e-01,  3.02017845e-01,
         3.55271368e-14],
       [ 5.09269733e-01,  3.68630551e-01,  2.53173107e-01,
        -4.17443857e-14],
       [-6.14595380e-01, -5.82128304e-01,  2.78519943e-01,
         1.00000000e+00]])

In [327]:
appxd1.shape

(3, 4)

In [328]:
appxd1[-1] = ([0]*(appxd1.shape[-1]-1)) + [1]

In [329]:
np.sum(np.abs(down1-appxd1))

1.6701286570139977

In [330]:
Ys_hat = down2 @ appxd1 @ up2 @ up1 @ Xs.T

In [331]:
down2 @ appxd1 @ up2 @ up1

array([[0.46406863, 1.1933581 ],
       [0.        , 1.        ]])

In [332]:
down2 @ down1 @ up2 @ up1

array([[0.41694524, 1.41692947],
       [0.        , 1.        ]])

In [333]:
Ys_hat.T

array([[1.32125168, 1.        ],
       [1.49253093, 1.        ],
       [1.29482174, 1.        ],
       [1.35126686, 1.        ],
       [1.619383  , 1.        ],
       [1.35877082, 1.        ],
       [1.46156709, 1.        ],
       [1.27646823, 1.        ],
       [1.54513583, 1.        ],
       [1.51272803, 1.        ],
       [1.54803969, 1.        ],
       [1.41906132, 1.        ],
       [1.36002154, 1.        ],
       [1.2272202 , 1.        ],
       [1.23229116, 1.        ],
       [1.33948431, 1.        ],
       [1.39703592, 1.        ],
       [1.55111793, 1.        ],
       [1.5199728 , 1.        ],
       [1.31003157, 1.        ]])

In [334]:
Ys.T

array([[1.53183623, 1.        ],
       [1.68572309, 1.        ],
       [1.50809009, 1.        ],
       [1.55880354, 1.        ],
       [1.7996941 , 1.        ],
       [1.56554552, 1.        ],
       [1.65790345, 1.        ],
       [1.49160027, 1.        ],
       [1.73298628, 1.        ],
       [1.70386931, 1.        ],
       [1.73559528, 1.        ],
       [1.61971389, 1.        ],
       [1.56666924, 1.        ],
       [1.44735308, 1.        ],
       [1.45190911, 1.        ],
       [1.54821744, 1.        ],
       [1.59992503, 1.        ],
       [1.73836094, 1.        ],
       [1.71037841, 1.        ],
       [1.52175545, 1.        ]])

In [335]:
np.mean((Ys_hat.T[:,0] - Ys.T[:,0])**2)

0.04089257248263724

In [336]:
np.mean(np.abs(Ys_hat.T[:,0] - Ys.T[:,0]))

0.2018864557511185